### ISSUE TITLE
No username on admin page

### ISSUE THREAD

**Issue by dsegovia90** [sego90/chingu#36]
There is no way to ask slack for the @username. We should remove it and maybe include the email address.

**Comment by AgathaLynn** [comment]
When handling requests from the /pair-programming slash command, we get the username but not the display name. We're currently using the username for more "friendly" user interactions within slack. 

I'd suggest keeping the username as is and closing this issue.

**Comment by sego90** [comment]
yep, you are right. Since you can get the username from the slack slash command.

**Comment by dsegovia90** [comment]
True that. The username is grabbed when using slack slash command.
