### ISSUE TITLE
Add install slack app button in dash 

### ISSUE THREAD

**Issue by dsegovia90** [sego90/chingu#37]
Add a install slack app button in dash if the app is not yet installed, and make the redirect to '/' since it will automatically redirect to login if the user is not logged in.

**Comment by dsegovia90** [comment]
Also, strongly suggest to install app before requesting a match for better results (since the app created the chat between the two).

**Comment by sego90** [comment]
merged the install-button branch to master

**Comment by dsegovia90** [comment]
merged the install-button branch to master
