### ISSUE TITLE
need to handle "access_denied" route after attempted install

### ISSUE THREAD

**Issue by AgathaLynn** [sego90/chingu#38]
We currently get an error message at this address: https://chingupp.herokuapp.com/auth/slack/install?error=access_denied

**Comment by dsegovia90** [comment]
fixed on branch handle-404-and-500.. I think we're missing a 404 catcher though.
I only fixed the error=access_denied

**Comment by dsegovia90** [comment]
There is an issue with our router. I can't seem to grasp the idea yet. I'm going to look into it on another issue and another branch.

**Comment by dsegovia90** [comment]
Ok, forget the handle-404-and-500 branch thing. I actually fixed the issue in the handle-universal-404 branch. Read de express documentation and we just needed to add the `next` parameter to the las function in app.js
